[package]
name = "funsomware"
version = "0.1.0"
edition = "2021"

[dependencies]
cryptify = "3.2.1"
rayon = "1.10"
walkdir = "2.5"
rand = "0.10"
native-dialog = "0.9.6"
dirs-next = "2.0"
wallpaper = "3.2.0"